name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - setuptools
  - rdkit=2023.03.1
  - scikit-learn=0.24.2
  - mljar-supervised=1.1.6
  - numpy=1.23.0
  - pandas=2.0.3
  - seaborn=0.12.2
  - matplotlib=3.7.2
  - mordred=1.2.0
  - streamlit=1.36.0
  - streamlit-ketcher=0.0.1
  - scipy=1.11.4
